In [1]:
import pandas as pd

In [2]:
path = r"C:\Tanish\Python\Pandas\Copy of Robot Game Accuracy Chart.xlsx"

In [3]:
sr = pd.Series(['42','45','12'])
sr

0    42
1    45
2    12
dtype: object

In [9]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60,
    "6":80
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102,
    "6":105
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127,
    "6":140
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300,
    "6":230
  }
}
df = pd.DataFrame(data)

In [10]:
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300
6        80    105       140       230

In [12]:
robo = pd.read_excel(path)

In [13]:
robo

,Launches,Launch 1,Launch 2,Launch 3,Launch 4,Launch 5,Launch 6,Launch 7,Launch 8,Launch 9,...,Launch 16,Launch 17,Launch 18,Launch 19,Launch 20,Launch 21,Launch 22,Launch 23,Launch 24,Launch 25
0,Hydroelectric Dam:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Hydroelectric Dam - Success - 20,20.000000,20,20,20,20,20,20,20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hydroelectric Dam - Time,7.330000,5.97,9.79,5.59,6.18,5,6.03,6.11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Innovation Project Model:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Innovation Project Model - Success - 10,10.000000,10,10,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Innovation Project Model - Time,6.420000,5.99,8.77,6.58,5.76,6.27,6.15,5.85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Power Plant:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Power Plant - Success - 15 - 5 each,15.000000,0,15,5,15,0,15,15,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Power Plant - Time,6.590000,NaN,6.48,10.23,6.5,4.66,6.27,6.41,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Power Plant - Bonus - 10,10.000000,0,10,0,10,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Stats:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Time Back,4.540000,12.72,4.62,4.09,4.77,6.09,4.76,4.78,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Total Time,24.880000,24.68,29.66,26.49,23.21,22.02,23.21,23.15,27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Total Points,55.000000,30,55,35,55,30,55,55,55,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Success Rate,1.000000,0.545455,1,0.636364,1,0.545455,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Full Completion,1.000000,0,1,0,1,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Notes:,NaN,Didn't do Power Plant,Got stuck on Water Dam,Got a bit stuck and only got the Right energy ...,Perfect Run,Lifted the first ring on poerplant but couldn'...,Perfect Run,Perfect Run,Perfect Run,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Average Points,47.222222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Average Points Converted,0.858586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Average Time,24.922222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Success Rate (Full Launch Completion),0.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Launches:,NaN,Launch 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Mission:,NaN,Hydroelectric Dam,Innovation Project Model,Power Plant,Total,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Points:,NaN,20,10,15,45,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Description:,NaN,If energy cell unit is not touching Water Dam.,If Innovation Project Model is partly inside H...,If energy cell unit is no longer touching Powe...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bonus:,NaN,0,0,10,10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Description:,NaN,NaN,NaN,If all three energy cell units are not touchin...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Total:,NaN,20,10,25,55,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
robo.fillna(0,inplace=True)

In [17]:
robo

,Launches,Launch 1,Launch 2,Launch 3,Launch 4,Launch 5,Launch 6,Launch 7,Launch 8,Launch 9,...,Launch 16,Launch 17,Launch 18,Launch 19,Launch 20,Launch 21,Launch 22,Launch 23,Launch 24,Launch 25
0,Hydroelectric Dam:,0.000000,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Hydroelectric Dam - Success - 20,20.000000,20,20,20,20,20,20,20,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Hydroelectric Dam - Time,7.330000,5.97,9.79,5.59,6.18,5,6.03,6.11,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Innovation Project Model:,0.000000,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Innovation Project Model - Success - 10,10.000000,10,10,10,10,10,10,10,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Innovation Project Model - Time,6.420000,5.99,8.77,6.58,5.76,6.27,6.15,5.85,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Power Plant:,0.000000,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Power Plant - Success - 15 - 5 each,15.000000,0,15,5,15,0,15,15,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Power Plant - Time,6.590000,0,6.48,10.23,6.5,4.66,6.27,6.41,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Power Plant - Bonus - 10,10.000000,0,10,0,10,0,10,10,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Stats:,0.000000,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Time Back,4.540000,12.72,4.62,4.09,4.77,6.09,4.76,4.78,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Total Time,24.880000,24.68,29.66,26.49,23.21,22.02,23.21,23.15,27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Total Points,55.000000,30,55,35,55,30,55,55,55,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Success Rate,1.000000,0.545455,1,0.636364,1,0.545455,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Full Completion,1.000000,0,1,0,1,0,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,Notes:,0.000000,Didn't do Power Plant,Got stuck on Water Dam,Got a bit stuck and only got the Right energy ...,Perfect Run,Lifted the first ring on poerplant but couldn'...,Perfect Run,Perfect Run,Perfect Run,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0,0.000000,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Average Points,47.222222,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,Average Points Converted,0.858586,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Average Time,24.922222,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Success Rate (Full Launch Completion),0.666667,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Launches:,0.000000,Launch 3,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,Mission:,0.000000,Hydroelectric Dam,Innovation Project Model,Power Plant,Total,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,Points:,0.000000,20,10,15,45,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Description:,0.000000,If energy cell unit is not touching Water Dam.,If Innovation Project Model is partly inside H...,If energy cell unit is no longer touching Powe...,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Bonus:,0.000000,0,0,10,10,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Description:,0.000000,0,0,If all three energy cell units are not touchin...,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Total:,0.000000,20,10,25,55,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
robo.tail()

,Launches,Launch 1,Launch 2,Launch 3,Launch 4,Launch 5,Launch 6,Launch 7,Launch 8,Launch 9,...,Launch 16,Launch 17,Launch 18,Launch 19,Launch 20,Launch 21,Launch 22,Launch 23,Launch 24,Launch 25
24,Points:,0.0,20,10,15,45,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Description:,0.0,If energy cell unit is not touching Water Dam.,If Innovation Project Model is partly inside H...,If energy cell unit is no longer touching Powe...,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Bonus:,0.0,0,0,10,10,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Description:,0.0,0,0,If all three energy cell units are not touchin...,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Total:,0.0,20,10,25,55,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
sub = robo.loc[robo["Launches"]=="Bonus: "]

In [27]:
robo.iloc[26,0:5] #robo.iloc[26,:]

In [32]:
sub.to_excel("Robo Sub.xlsx",index=False)

In [33]:
sub.to_csv("Robo Sub.csv")